server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tandaBase?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12313

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
